name: Menu
main: me.eric.menu.Main
version: 1.0
author: EricSiu
api-version: 1.13
commands:
  shadoshi:
    description: Opens the server menu.
    aliases: [menu, servermenu]
    permission: menu.shadoshi
    permission-message: You do not have permission menu.shadoshi
permissions:
  menu.shadoshi:
    description: Allows you to use /shadoshi.
    default: true